version: "3.7"
services:
  triton:
    image: triton-rust
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes:
      - "/home/mi/Documents/code/triton/backend/examples/model_repos/minimal_models:/models"
      - ${PWD}/:/workspace/exp-mini-backend
    command: sleep infinity  
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    environment:
      - CPATH=/opt/tritonserver/include:$CPATH

