version: "3.7"
services:
  triton:
    image: triton-rust
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes:
      - ${PWD}/model_repos/minimal_models:/models"
      - ${PWD}/../:/workspace/exp-mini-backend
    command: sleep infinity  
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    network_mode: "host"


