version: "3.7"
services:
  triton:
    image: triton-rust
      # user: 1000:1000
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes:
      - ${PWD}/model_repos/minimal_models:/models"
      - ${PWD}/../:/workspace/exp-mini-backend
    command: sleep infinity  
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    network_mode: "host"
    environment:
      JULIA_DIR: "/opt/tritonserver/julia-1.8.5"
      LD_LIBRARY_PATH: "/opt/tritonserver/julia-1.8.5/lib/:$LD_LIBRARY_PATH"
      PATH: "$PATH:/opt/tritonserver/julia-1.8.5/bin/"


